import { ArrowRight, CheckCircle2 } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NotFound from "@/pages/NotFound";
import { usePageSeo, useStructuredData } from "@/hooks/usePageSeo";
import { whatsappUrl } from "@/lib/whatsapp";
import blueprintsHero from "@/assets/service-heroes/blueprints.jpg";
import constructionHero from "@/assets/service-heroes/construction.jpg";
import engineerHero from "@/assets/service-heroes/engineer.jpg";
import planningHero from "@/assets/service-heroes/planning.jpg";
import projectHero from "@/assets/service-heroes/project.jpg";
import solarHero from "@/assets/service-heroes/solar.jpg";
import teamHero from "@/assets/service-heroes/team.jpg";
import topographyHero from "@/assets/service-heroes/topography.jpg";

const services = {
  "bureau-etudes-mali": { eyebrow: "Ingénierie conseil", title: "Bureau d'études au Mali", intro: "ICRED est un bureau d'études techniques au Mali qui accompagne les projets publics et privés avec une approche concrète, fiable et adaptée au terrain.", keywords: "Bureau d'études Mali · Bureau d'études Bamako · Ingénierie Mali · Ingénieur conseil Mali", benefits: ["Études et conseil sur mesure", "Coordination d'expertises techniques", "Accompagnement des collectivités, entreprises et partenaires au développement"], sections: [["Un partenaire pour chaque étape", "Notre bureau d'études à Bamako intervient dès l'émergence du besoin et reste présent jusqu'à la réception des ouvrages. Nous analysons votre contexte, précisons les objectifs, identifions les contraintes du terrain et organisons les expertises utiles. Cette vision globale permet de prendre les bonnes décisions avant d'engager des dépenses importantes."], ["Une expertise technique pluridisciplinaire", "Selon la nature de votre projet, ICRED mobilise des compétences en infrastructures, bâtiment, eau et assainissement, énergie, environnement, aménagement ou développement territorial. Cette coordination évite les études isolées et assure la cohérence entre les choix techniques, les besoins réels des usagers et les ressources disponibles."], ["Des livrables clairs pour décider", "Notre accompagnement peut aboutir à des diagnostics, notes de cadrage, avant-projets, plans, estimations, dossiers techniques, cahiers des charges ou rapports de suivi. Nous présentons les résultats dans un langage exploitable par les décideurs, les bailleurs, les entreprises et les équipes de terrain."], ["Une ingénierie adaptée au contexte malien", "La réussite d'un projet ne dépend pas seulement des normes et des calculs. Elle dépend aussi de l'accessibilité des sites, des saisons, des matériaux disponibles, des capacités locales et des contraintes d'exploitation. Nos ingénieurs conseils intègrent ces réalités pour proposer des solutions durables, réalistes et maîtrisées."]] },
  "topographie-mali": { eyebrow: "Mesure & terrain", title: "Topographie au Mali", intro: "Nos prestations de topographie au Mali fournissent les données précises nécessaires pour concevoir, implanter et suivre vos projets d'infrastructure ou d'aménagement.", keywords: "Topographie Mali · Topographe Bamako · Levé topographique Mali · Étude topographique Mali · Relevé topographique Bamako", benefits: ["Levé et relevé topographique", "Implantation et contrôle d'ouvrages", "Plans, profils et données exploitables"], sections: [["La précision comme point de départ", "Un projet bien conçu repose sur une bonne connaissance du terrain. Nos topographes à Bamako réalisent les levés topographiques, nivellements, implantations et contrôles nécessaires pour disposer de données fiables avant de dessiner, chiffrer ou construire. Chaque intervention est préparée selon la précision attendue et les contraintes d'accès au site."], ["Du terrain aux documents exploitables", "Après les relevés, nous traitons et vérifions les données afin de fournir des plans de situation, plans topographiques, courbes de niveau, profils en long, profils en travers ou coordonnées d'implantation. Ces documents permettent aux architectes, ingénieurs, entreprises et maîtres d'ouvrage de travailler sur une base commune."], ["Des usages pour tous les types de projets", "Nos études topographiques soutiennent les projets routiers, bâtiments, réseaux d'eau, lotissements, périmètres agricoles, carrières et ouvrages de génie civil. Elles servent également à préparer les études de drainage, à calculer des terrassements ou à contrôler l'avancement et les quantités exécutées."], ["Implantation et contrôle sur chantier", "La mission ne s'arrête pas au relevé initial. ICRED peut implanter les axes, niveaux et ouvrages prévus, puis vérifier leur positionnement pendant les travaux. Ce contrôle limite les erreurs coûteuses, facilite le dialogue entre intervenants et sécurise la conformité de l'exécution."]] },
  "etudes-techniques-mali": { eyebrow: "Conception & expertise", title: "Études techniques & ingénierie au Mali", intro: "ICRED réalise des études techniques au Mali pour transformer une intention de projet en une solution cohérente, chiffrée et réalisable.", keywords: "Études techniques Mali · Ingénierie conseil Mali · Étude technique bâtiment Mali · Ingénierie Bamako · Études d'ingénierie Mali", benefits: ["Diagnostic et analyse des besoins", "Avant-projets et dossiers techniques", "Solutions optimisées pour le contexte local"], sections: [["Transformer une idée en solution réalisable", "Nos études techniques au Mali structurent les choix à effectuer avant le lancement : besoins, usages, contraintes foncières, conditions d'accès, raccordements, matériaux et niveaux de performance attendus. Cette phase réduit les incertitudes et permet de construire un projet cohérent dès le départ."], ["Une démarche d'ingénierie en plusieurs étapes", "Nous commençons par le diagnostic et la collecte des informations disponibles. Nous élaborons ensuite les variantes, les avant-projets et les recommandations techniques, puis préparons les éléments nécessaires à la consultation ou à l'exécution. Chaque étape est expliquée afin que le maître d'ouvrage conserve une vision claire des arbitrages."], ["Bâtiment, infrastructures, eau et énergie", "Notre ingénierie conseil intervient notamment pour les études techniques de bâtiment, réseaux d'eau potable, assainissement, installations énergétiques, routes et aménagements. Nous dimensionnons les solutions avec le souci de leur faisabilité, de leur maintenance future et de leur compatibilité avec le budget du projet."], ["Des dossiers qui facilitent la mise en œuvre", "Les études d'ingénierie peuvent comprendre des notes de calcul, plans, quantitatifs, estimations, prescriptions techniques et dossiers d'appel d'offres. Des documents précis facilitent la comparaison des offres, la sélection des entreprises et le contrôle de la qualité pendant les travaux."]] },
  "genie-civil-mali": { eyebrow: "Chantier & contrôle", title: "Génie civil & suivi des travaux au Mali", intro: "Pour vos projets de génie civil au Mali, ICRED assure les études, le suivi des travaux et le contrôle technique nécessaires à une exécution maîtrisée.", keywords: "Génie civil Mali · Bureau d'études génie civil Mali · Suivi travaux Mali · Contrôle travaux Bamako · Ingénieur génie civil Mali", benefits: ["Études de structures et ouvrages", "Suivi de chantier et contrôle qualité", "Rapports réguliers et assistance au maître d'ouvrage"], sections: [["Un chantier sous contrôle", "Nos ingénieurs en génie civil suivent la conformité des travaux avec les plans, les spécifications, les quantités et le calendrier convenu. Lors des visites de chantier, nous observons les points sensibles, relevons les écarts éventuels et formulons des recommandations utiles au maître d'ouvrage et aux entreprises."], ["Un suivi régulier et traçable", "Le suivi des travaux ne consiste pas uniquement à constater l'avancement. ICRED met en place des comptes rendus de visites, rapports d'avancement, tableaux de suivi et échanges structurés avec les intervenants. Cette traçabilité aide à anticiper les retards, à documenter les décisions et à maîtriser les modifications en cours de chantier."], ["Des ouvrages conçus pour durer", "Bâtiments, routes, réseaux, ouvrages d'art et aménagements doivent répondre aux usages prévus et résister aux conditions locales. Nous veillons à la qualité des matériaux, au respect des méthodes d'exécution, à la gestion des interfaces techniques et aux exigences de sécurité tout au long du projet."], ["Assistance au maître d'ouvrage", "ICRED peut représenter les intérêts techniques du client face aux entreprises. Nous participons à l'analyse des offres, aux réunions de chantier, à la vérification des attachements et aux opérations de réception. Vous bénéficiez ainsi d'une lecture indépendante pour prendre des décisions éclairées."]] },
  "etude-faisabilite-mali": { eyebrow: "Décision & stratégie", title: "Études de faisabilité & conseil au Mali", intro: "Avant d'engager un investissement, une étude de faisabilité au Mali vous permet de valider la pertinence, les contraintes et la viabilité de votre projet.", keywords: "Étude de faisabilité Mali · Conseil en ingénierie Mali · Étude de projet Mali · Étude de faisabilité projet · Conseil technique Mali", benefits: ["Analyse des besoins et du contexte", "Évaluation technique, économique et des risques", "Scénarios clairs pour décider sereinement"], sections: [["Sécuriser un investissement dès l'amont", "Une étude de faisabilité permet de vérifier qu'une idée de projet répond à un besoin réel et peut être mise en œuvre dans de bonnes conditions. ICRED analyse le contexte, les bénéficiaires, les objectifs, le site, les ressources nécessaires et les principales contraintes avant que des engagements importants soient pris."], ["Évaluer les options et les risques", "Nous comparons les solutions techniques envisageables et apprécions leurs effets sur le coût, le délai, l'exploitation et la maintenance. L'étude identifie également les risques opérationnels, environnementaux, fonciers ou organisationnels afin de prévoir des mesures réalistes pour les réduire."], ["Un cadre utile pour le financement", "Pour convaincre un partenaire, un bailleur ou une direction, il faut présenter un projet précis et argumenté. Nos études de projet rassemblent les données techniques, les estimations budgétaires, le calendrier indicatif et les hypothèses de mise en œuvre nécessaires à une décision de financement ou de programmation."], ["Passer de la décision à l'action", "À l'issue de la mission, nous proposons un scénario recommandé et une feuille de route. Celle-ci peut inclure les études détaillées à engager, les autorisations à prévoir, le montage de consultation et les étapes de suivi. Vous disposez d'une base concrète pour lancer le projet avec davantage de visibilité."]] },
  "ingenierie-conseil-mali": { eyebrow: "Expertise & stratégie", title: "Ingénierie & conseil au Mali", intro: "ICRED met à votre disposition un ingénieur conseil au Mali pour analyser vos besoins, sécuriser vos choix techniques et orienter la réalisation de vos projets.", keywords: "Ingénieur conseil Mali · Ingénieur consultant Mali · Cabinet ingénierie Mali · Conseil en ingénierie Mali", benefits: ["Conseil technique indépendant", "Analyse des options et des risques", "Accompagnement des décisions de projet"], sections: [["Un ingénieur conseil pour vos projets au Mali", "Notre équipe d'ingénieurs conseils accompagne les organisations, entreprises et collectivités de Bamako et du Mali dans la définition, la conception et le suivi de leurs projets. Nous apportons une lecture technique claire avant les décisions importantes."], ["Conseil en ingénierie adapté au terrain", "Chaque mission tient compte du site, du budget, des usages, des contraintes réglementaires et de l'exploitation future. Notre cabinet d'ingénierie au Mali propose des recommandations réalistes et adaptées au contexte local."], ["Du diagnostic à la décision", "Nous pouvons examiner une idée, relire un dossier, comparer des solutions ou organiser les études nécessaires. Cette approche aide les maîtres d'ouvrage à réduire les incertitudes et à avancer avec une feuille de route précise."]] },
  "etude-projet-mali": { eyebrow: "Conception de projet", title: "Étude de projet au Mali", intro: "ICRED réalise des études de projet au Mali pour structurer les besoins, définir les solutions techniques et préparer une mise en œuvre maîtrisée.", keywords: "Étude de projet Mali · Étude technique de projet Mali · Conception de projet Mali · Bureau étude projet Mali", benefits: ["Cadrage des besoins", "Scénarios techniques et chiffrés", "Dossiers exploitables pour la décision"], sections: [["Concevoir un projet solide", "Une étude de projet transforme une intention en plan d'action. Notre bureau d'étude de projet au Mali analyse les objectifs, le site, les besoins des usagers et les moyens nécessaires pour établir une solution cohérente."], ["Étude technique de projet", "Nous préparons les données, les variantes, les plans et les estimations utiles à la conception de projet au Mali. Les livrables facilitent les arbitrages, la recherche de financement et la consultation des entreprises."], ["Préparer la réalisation", "Selon la nature du projet, l'étude peut intégrer le calendrier, les prescriptions techniques, les quantités et les principaux risques. Vous disposez ainsi d'une base claire pour passer à l'étape suivante."]] },
  "entreprise-btp-mali": { eyebrow: "BTP & construction", title: "Entreprise BTP au Mali", intro: "ICRED accompagne les projets de BTP au Mali par les études, la coordination technique, le contrôle et le suivi des travaux de construction.", keywords: "Entreprise BTP Mali · Entreprise BTP Bamako · BTP Mali · Travaux publics Mali · Entreprise construction Mali", benefits: ["Études et préparation des travaux", "Suivi et contrôle de chantier", "Coordination des intervenants"], sections: [["Accompagnement des projets BTP au Mali", "Pour les bâtiments, équipements, ouvrages et travaux publics au Mali, ICRED apporte son expertise de bureau d'études. Nous intervenons en amont pour préparer les travaux puis pendant l'exécution pour contrôler la qualité et l'avancement."], ["Construction et travaux publics à Bamako", "Notre équipe accompagne les maîtres d'ouvrage dans la définition des ouvrages, l'analyse des offres, le suivi des entreprises de construction et la réception des travaux. Chaque intervention s'adapte au programme et aux contraintes du chantier."], ["Un suivi rigoureux des travaux", "Plans, quantités, délais, qualité des matériaux et sécurité : nous vérifions les éléments déterminants pour aider à sécuriser les projets BTP et les infrastructures au Mali."]] },
  "forage-eau-mali": { eyebrow: "Eau & hydraulique", title: "Forage d'eau au Mali", intro: "ICRED accompagne les projets de forage d'eau au Mali, de l'étude du besoin à la conception des systèmes d'adduction d'eau potable.", keywords: "Forage eau Mali · Entreprise de forage au Mali · Forage Mali Bamako · Prix d'un forage au Mali · Prix forage Bamako", benefits: ["Études hydrogéologiques et techniques", "Conception d'adduction d'eau", "Appui au suivi des travaux de forage"], sections: [["Préparer un forage d'eau fiable", "Un projet de forage eau au Mali demande une bonne compréhension du besoin, du site et de la ressource. ICRED réalise les études et dossiers techniques nécessaires avant la consultation des entreprises de forage au Mali."], ["Du forage à l'adduction d'eau", "Nos prestations peuvent couvrir le dimensionnement du captage, du pompage, du stockage et des réseaux d'adduction d'eau. Nous adaptons la solution aux usages, à la population desservie et aux conditions d'exploitation."], ["Coût et faisabilité d'un forage au Mali", "Le prix d'un forage au Mali dépend notamment du contexte géologique, de la profondeur, du débit recherché, des équipements et du réseau à réaliser. Une étude préalable permet de chiffrer le projet avec des hypothèses transparentes."]] },
  "energie-solaire-mali": { eyebrow: "Énergie & photovoltaïque", title: "Énergie solaire au Mali", intro: "ICRED conçoit et accompagne des projets d'énergie solaire au Mali : études, dimensionnement et suivi de solutions photovoltaïques fiables.", keywords: "Entreprise énergie solaire Mali · Entreprise solaire Bamako · Installation solaire Mali · Installation photovoltaïque Mali · Panneaux solaires Mali", benefits: ["Études de faisabilité solaire", "Dimensionnement photovoltaïque", "Suivi d'installation et hybridation"], sections: [["Une entreprise d'énergie solaire au Mali", "ICRED accompagne les entreprises, collectivités et porteurs de projets qui souhaitent développer une installation solaire au Mali. Nos ingénieurs évaluent les besoins, les usages et les contraintes du site afin de proposer une solution photovoltaïque pertinente."], ["Étude et dimensionnement photovoltaïque", "Nous analysons la consommation, le potentiel solaire, les options de stockage et d'hybridation. Cette étude permet de définir les équipements, les performances attendues et les conditions de maintenance avant toute installation photovoltaïque au Mali."], ["Panneaux solaires et décision d'investissement", "Le choix de panneaux solaires au Mali ne se limite pas au prix : il dépend du besoin énergétique, du dimensionnement, de la qualité des équipements et de la durée d'exploitation. Nous apportons une expertise technique indépendante pour comparer les scénarios."]] },
  "etude-environnementale-mali": { eyebrow: "Environnement & conformité", title: "Étude environnementale au Mali", intro: "ICRED réalise des études environnementales au Mali, incluant les études d'impact environnemental et social nécessaires aux projets d'aménagement et d'infrastructure.", keywords: "Étude environnementale Mali · Étude d'impact environnemental Mali · EIES Mali · Cabinet environnement Mali", benefits: ["Analyse des impacts", "Mesures environnementales et sociales", "Accompagnement des procédures"], sections: [["Étude environnementale pour vos projets", "Notre cabinet environnement au Mali accompagne les porteurs de projets dans l'identification des impacts, des risques et des mesures à prévoir. Cette démarche contribue à concevoir des projets responsables et compatibles avec leur milieu."], ["Étude d'impact environnemental et social", "Une EIES au Mali permet d'évaluer les effets potentiels d'un projet sur l'environnement et les populations. ICRED collecte les données, analyse les enjeux et prépare des recommandations et plans de gestion adaptés."], ["Un appui de la conception au suivi", "Au-delà de l'étude d'impact environnemental au Mali, nous pouvons intégrer les exigences environnementales dans les dossiers techniques et accompagner le suivi des mesures pendant les travaux."]] },
  "travaux-routiers-mali": { eyebrow: "Routes & infrastructures", title: "Travaux routiers & infrastructures au Mali", intro: "ICRED accompagne les projets de travaux routiers au Mali par les études, la conception et le suivi des routes, pistes rurales, ponts et ouvrages d'infrastructure.", keywords: "Travaux routiers Mali · Construction route Mali · Infrastructures routières Mali · Construction pont Mali · Pistes rurales Mali · Entreprise travaux publics Mali", benefits: ["Études routières et hydrauliques", "Conception des ouvrages", "Suivi et contrôle des travaux"], sections: [["Études et suivi des travaux routiers", "ICRED intervient sur les travaux routiers au Mali depuis les études préliminaires jusqu'au contrôle de l'exécution. Nous accompagnons les projets de construction de route, de voirie et de pistes rurales avec une approche adaptée au terrain."], ["Infrastructures routières et ouvrages d'art", "Nos équipes réalisent les études nécessaires aux routes, ponts, ouvrages de drainage et autres infrastructures routières au Mali. Les solutions sont dimensionnées selon les trafics, l'hydrologie, les matériaux et les contraintes locales."], ["Un partenaire pour les travaux publics", "Pour les maîtres d'ouvrage et entreprises de travaux publics au Mali, nous proposons une expertise de conception, de contrôle et de suivi afin d'améliorer la qualité, les délais et la durabilité des ouvrages."]] },
} as const;

const seoKeywords: Record<string, string> = {
  "bureau-etudes-mali": "bureau d'études Mali, bureau d'études, bureau d'études Bamako, bureau d'études techniques Mali, bureau d'études BTP Mali",
  "genie-civil-mali": "entreprise génie civil Mali, génie civil Mali, entreprise génie civil Bamako, travaux de génie civil Mali",
  "topographie-mali": "topographie Mali, topographe Mali, topographe Bamako, entreprise de topographie Mali, étude topographique Mali, relevé topographique Mali",
  "etudes-techniques-mali": "études techniques Mali, études techniques, étude technique bâtiment Mali, étude technique construction Mali, études techniques infrastructures Mali",
  "ingenierie-conseil-mali": "ingénieur conseil Mali, ingénieur consultant Mali, cabinet ingénierie Mali, conseil en ingénierie Mali",
  "etude-faisabilite-mali": "étude de faisabilité Mali, étude de faisabilité projet Mali, étude de faisabilité technique Mali, cabinet étude de faisabilité Mali",
  "etude-projet-mali": "étude de projet Mali, étude technique de projet Mali, conception de projet Mali, bureau étude projet Mali",
  "entreprise-btp-mali": "entreprise BTP Mali, entreprise BTP Bamako, BTP Mali, travaux publics Mali, entreprise construction Mali",
  "forage-eau-mali": "forage eau Mali, entreprise de forage au Mali, forage Mali Bamako, prix d'un forage au Mali, prix forage Bamako",
  "energie-solaire-mali": "entreprise énergie solaire Mali, entreprise d'énergie solaire au Mali, entreprise solaire Bamako, installation solaire Mali, installation photovoltaïque Mali, panneaux solaires Mali",
  "etude-environnementale-mali": "étude environnementale Mali, étude d'impact environnemental Mali, EIES Mali, cabinet environnement Mali",
  "travaux-routiers-mali": "travaux routiers Mali, construction route Mali, infrastructures routières Mali, construction pont Mali, pistes rurales Mali, entreprise travaux publics Mali",
};

const serviceHeroImages: Record<string, string> = {
  "bureau-etudes-mali": engineerHero,
  "topographie-mali": topographyHero,
  "etudes-techniques-mali": blueprintsHero,
  "genie-civil-mali": constructionHero,
  "ingenierie-conseil-mali": teamHero,
  "etude-faisabilite-mali": planningHero,
  "etude-projet-mali": projectHero,
  "entreprise-btp-mali": constructionHero,
  "forage-eau-mali": planningHero,
  "energie-solaire-mali": solarHero,
  "etude-environnementale-mali": teamHero,
  "travaux-routiers-mali": constructionHero,
};

const serviceLinks = {
  "bureau-etudes-mali": ["etudes-techniques-mali", "etude-faisabilite-mali", "ingenierie-conseil-mali"],
  "topographie-mali": ["etudes-techniques-mali", "genie-civil-mali", "travaux-routiers-mali"],
  "etudes-techniques-mali": ["etude-projet-mali", "topographie-mali", "etude-faisabilite-mali"],
  "genie-civil-mali": ["etudes-techniques-mali", "topographie-mali", "travaux-routiers-mali"],
  "etude-faisabilite-mali": ["etude-projet-mali", "etude-environnementale-mali", "ingenierie-conseil-mali"],
  "ingenierie-conseil-mali": ["bureau-etudes-mali", "etudes-techniques-mali", "etude-faisabilite-mali"],
  "etude-projet-mali": ["etudes-techniques-mali", "etude-faisabilite-mali", "genie-civil-mali"],
  "entreprise-btp-mali": ["genie-civil-mali", "etudes-techniques-mali", "travaux-routiers-mali"],
  "forage-eau-mali": ["etudes-techniques-mali", "energie-solaire-mali", "etude-environnementale-mali"],
  "energie-solaire-mali": ["etude-faisabilite-mali", "etudes-techniques-mali", "forage-eau-mali"],
  "etude-environnementale-mali": ["etude-faisabilite-mali", "etude-projet-mali", "travaux-routiers-mali"],
  "travaux-routiers-mali": ["topographie-mali", "etudes-techniques-mali", "genie-civil-mali"],
} as const;

const ServiceDetail = () => {
  const { slug } = useParams();
  const service = services[slug as keyof typeof services];
  const pageUrl = `https://icred-mali.com/${slug ?? ""}/`;
  const heroImage = serviceHeroImages[slug ?? ""] ?? engineerHero;
  const relatedServices = (serviceLinks[slug as keyof typeof serviceLinks] ?? []).map((relatedSlug) => ({
    slug: relatedSlug,
    title: services[relatedSlug].title,
    intro: services[relatedSlug].intro,
  }));
  usePageSeo(
    service ? `${service.title} | ICRED Mali` : "Page introuvable | ICRED Mali",
    service?.intro ?? "Cette page n'existe pas ou a été déplacée.",
    `/${slug ?? ""}`,
    "website",
    seoKeywords[slug ?? ""] ?? "",
    { image: heroImage, robots: service ? undefined : "noindex, follow" },
  );
  useStructuredData(`service-schema-${slug}`, service ? {
    "@context": "https://schema.org",
    "@graph": [
      { "@type": "Service", name: service.title, description: service.intro, keywords: seoKeywords[slug ?? ""], provider: { "@id": "https://icred-mali.com/#organization", "@type": "ProfessionalService", name: "ICRED Mali SARL", telephone: "+22376085847", address: { "@type": "PostalAddress", addressLocality: "Bamako", addressCountry: "ML" } }, areaServed: { "@type": "Country", name: "Mali" }, url: pageUrl, serviceType: service.eyebrow, offers: { "@type": "Offer", availability: "https://schema.org/InStock", areaServed: "Mali", priceCurrency: "XOF", url: pageUrl } },
      { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Accueil", item: "https://icred-mali.com/" }, { "@type": "ListItem", position: 2, name: "Services", item: "https://icred-mali.com/services/" }, { "@type": "ListItem", position: 3, name: service.title, item: pageUrl }] },
      { "@type": "FAQPage", mainEntity: [
        { "@type": "Question", name: `Pourquoi faire appel à ICRED pour ${service.title.toLowerCase()} ?`, acceptedAnswer: { "@type": "Answer", text: "ICRED apporte une expertise locale, une méthodologie structurée et un accompagnement adapté aux contraintes de chaque projet au Mali." } },
        { "@type": "Question", name: "Comment demander un devis ou un accompagnement ?", acceptedAnswer: { "@type": "Answer", text: "Contactez ICRED par téléphone, WhatsApp ou via le formulaire de contact afin de présenter votre besoin et recevoir une réponse adaptée." } }
      ] }
    ]
  } : {});
  if (!service) return <NotFound />;
  return <div className="min-h-screen bg-background"><Navbar /><main>
    <section className="relative isolate overflow-hidden pt-36 pb-20 px-4 text-primary-foreground"><img src={heroImage} alt="" className="absolute inset-0 -z-20 h-full w-full object-cover" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-primary/95 via-primary/85 to-primary/55" /><div className="container mx-auto max-w-5xl"><p className="text-secondary font-semibold uppercase tracking-[.2em] text-xs mb-5">{service.eyebrow}</p><h1 className="text-4xl md:text-6xl font-bold max-w-4xl">{service.title}</h1><p className="mt-6 text-lg leading-relaxed text-primary-foreground/85 max-w-3xl">{service.intro}</p><p className="mt-7 text-sm text-primary-foreground/70 border-l-2 border-secondary pl-4">{service.keywords}</p></div></section>
    <section className="section-padding"><div className="container mx-auto max-w-5xl grid lg:grid-cols-[1fr_.7fr] gap-12"><div className="space-y-10">{service.sections.map(([heading, text]) => <article key={heading}><h2 className="text-3xl font-bold mb-4">{heading}</h2><p className="text-muted-foreground leading-8 text-lg">{text}</p></article>)}</div><aside className="rounded-2xl bg-card border border-border p-7 h-fit"><h2 className="text-2xl font-bold mb-6">Notre accompagnement</h2><ul className="space-y-4">{service.benefits.map((benefit) => <li key={benefit} className="flex gap-3 text-foreground/80"><CheckCircle2 className="shrink-0 text-primary" size={20}/>{benefit}</li>)}</ul><a href={whatsappUrl(`Bonjour ICRED, je souhaite parler de mon projet de ${service.title.toLowerCase()}.`)} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex items-center gap-2 bg-gradient-primary text-primary-foreground px-5 py-3 rounded-lg font-semibold">Parler de votre projet <ArrowRight size={17}/></a></aside></div></section>
    <section className="px-4 pb-20"><div className="container mx-auto max-w-5xl"><div className="max-w-3xl mb-8"><p className="text-primary font-semibold mb-2">Expertises complémentaires</p><h2 className="text-3xl font-bold">Des services qui se complètent</h2><p className="mt-4 text-muted-foreground leading-8">Un projet solide mobilise souvent plusieurs compétences : connaissance du terrain, étude, préparation des travaux, suivi et prise en compte des impacts. Découvrez les expertises ICRED qui complètent cette prestation.</p></div><div className="grid gap-5 md:grid-cols-3">{relatedServices.map((related) => <Link key={related.slug} to={`/${related.slug}`} className="rounded-2xl border border-border bg-card p-6 transition-shadow hover:shadow-card"><h3 className="text-xl font-bold text-foreground">{related.title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{related.intro}</p><span className="mt-5 inline-flex items-center gap-2 font-semibold text-primary">Découvrir ce service <ArrowRight size={16}/></span></Link>)}</div></div></section>
    <section className="px-4 pb-20"><div className="container mx-auto max-w-5xl bg-green-pale rounded-2xl p-8 md:p-12 flex flex-col md:flex-row justify-between gap-6 items-start"><div><p className="text-primary font-semibold mb-2">ICRED Mali</p><h2 className="text-3xl font-bold">Besoin d'un autre savoir-faire ?</h2><p className="mt-3 text-muted-foreground">Parcourez l'ensemble de nos expertises pour construire un accompagnement adapté à votre projet.</p></div><Link to="/services" className="inline-flex items-center gap-2 font-semibold text-primary">Voir tous nos services <ArrowRight size={17}/></Link></div></section>
    <section className="px-4 pb-20"><div className="container mx-auto max-w-5xl"><h2 className="text-3xl font-bold mb-7">Questions fréquentes</h2><div className="grid md:grid-cols-2 gap-5"><article className="rounded-xl border border-border bg-card p-6"><h3 className="text-xl font-bold mb-3">Pourquoi choisir ICRED ?</h3><p className="text-muted-foreground leading-relaxed">ICRED associe expertise technique, connaissance du terrain malien et écoute attentive de vos objectifs de projet.</p></article><article className="rounded-xl border border-border bg-card p-6"><h3 className="text-xl font-bold mb-3">Comment obtenir un accompagnement ?</h3><p className="text-muted-foreground leading-relaxed">Présentez-nous votre besoin par téléphone, WhatsApp ou via le formulaire de contact ; notre équipe vous orientera vers la solution adaptée.</p></article></div></div></section>
  </main><Footer /></div>;
};
export default ServiceDetail;
