import { ArrowRight, CheckCircle2 } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { usePageSeo, useStructuredData } from "@/hooks/usePageSeo";
import { whatsappUrl } from "@/lib/whatsapp";

const services = {
  "bureau-etudes-mali": { eyebrow: "Ingénierie conseil", title: "Bureau d'études au Mali", intro: "ICRED est un bureau d'études techniques au Mali qui accompagne les projets publics et privés avec une approche concrète, fiable et adaptée au terrain.", keywords: "Bureau d'études Mali · Bureau d'études Bamako · Ingénierie Mali · Ingénieur conseil Mali", benefits: ["Études et conseil sur mesure", "Coordination d'expertises techniques", "Accompagnement des collectivités, entreprises et partenaires au développement"], sections: [["Un partenaire pour chaque étape", "Notre bureau d'études à Bamako intervient dès l'émergence du besoin et reste présent jusqu'à la réception des ouvrages. Nous analysons votre contexte, précisons les objectifs, identifions les contraintes du terrain et organisons les expertises utiles. Cette vision globale permet de prendre les bonnes décisions avant d'engager des dépenses importantes."], ["Une expertise technique pluridisciplinaire", "Selon la nature de votre projet, ICRED mobilise des compétences en infrastructures, bâtiment, eau et assainissement, énergie, environnement, aménagement ou développement territorial. Cette coordination évite les études isolées et assure la cohérence entre les choix techniques, les besoins réels des usagers et les ressources disponibles."], ["Des livrables clairs pour décider", "Notre accompagnement peut aboutir à des diagnostics, notes de cadrage, avant-projets, plans, estimations, dossiers techniques, cahiers des charges ou rapports de suivi. Nous présentons les résultats dans un langage exploitable par les décideurs, les bailleurs, les entreprises et les équipes de terrain."], ["Une ingénierie adaptée au contexte malien", "La réussite d'un projet ne dépend pas seulement des normes et des calculs. Elle dépend aussi de l'accessibilité des sites, des saisons, des matériaux disponibles, des capacités locales et des contraintes d'exploitation. Nos ingénieurs conseils intègrent ces réalités pour proposer des solutions durables, réalistes et maîtrisées."]] },
  "topographie-mali": { eyebrow: "Mesure & terrain", title: "Topographie au Mali", intro: "Nos prestations de topographie au Mali fournissent les données précises nécessaires pour concevoir, implanter et suivre vos projets d'infrastructure ou d'aménagement.", keywords: "Topographie Mali · Topographe Bamako · Levé topographique Mali · Étude topographique Mali · Relevé topographique Bamako", benefits: ["Levé et relevé topographique", "Implantation et contrôle d'ouvrages", "Plans, profils et données exploitables"], sections: [["La précision comme point de départ", "Un projet bien conçu repose sur une bonne connaissance du terrain. Nos topographes à Bamako réalisent les levés topographiques, nivellements, implantations et contrôles nécessaires pour disposer de données fiables avant de dessiner, chiffrer ou construire. Chaque intervention est préparée selon la précision attendue et les contraintes d'accès au site."], ["Du terrain aux documents exploitables", "Après les relevés, nous traitons et vérifions les données afin de fournir des plans de situation, plans topographiques, courbes de niveau, profils en long, profils en travers ou coordonnées d'implantation. Ces documents permettent aux architectes, ingénieurs, entreprises et maîtres d'ouvrage de travailler sur une base commune."], ["Des usages pour tous les types de projets", "Nos études topographiques soutiennent les projets routiers, bâtiments, réseaux d'eau, lotissements, périmètres agricoles, carrières et ouvrages de génie civil. Elles servent également à préparer les études de drainage, à calculer des terrassements ou à contrôler l'avancement et les quantités exécutées."], ["Implantation et contrôle sur chantier", "La mission ne s'arrête pas au relevé initial. ICRED peut implanter les axes, niveaux et ouvrages prévus, puis vérifier leur positionnement pendant les travaux. Ce contrôle limite les erreurs coûteuses, facilite le dialogue entre intervenants et sécurise la conformité de l'exécution."]] },
  "etudes-techniques-mali": { eyebrow: "Conception & expertise", title: "Études techniques & ingénierie au Mali", intro: "ICRED réalise des études techniques au Mali pour transformer une intention de projet en une solution cohérente, chiffrée et réalisable.", keywords: "Études techniques Mali · Ingénierie conseil Mali · Étude technique bâtiment Mali · Ingénierie Bamako · Études d'ingénierie Mali", benefits: ["Diagnostic et analyse des besoins", "Avant-projets et dossiers techniques", "Solutions optimisées pour le contexte local"], sections: [["Transformer une idée en solution réalisable", "Nos études techniques au Mali structurent les choix à effectuer avant le lancement : besoins, usages, contraintes foncières, conditions d'accès, raccordements, matériaux et niveaux de performance attendus. Cette phase réduit les incertitudes et permet de construire un projet cohérent dès le départ."], ["Une démarche d'ingénierie en plusieurs étapes", "Nous commençons par le diagnostic et la collecte des informations disponibles. Nous élaborons ensuite les variantes, les avant-projets et les recommandations techniques, puis préparons les éléments nécessaires à la consultation ou à l'exécution. Chaque étape est expliquée afin que le maître d'ouvrage conserve une vision claire des arbitrages."], ["Bâtiment, infrastructures, eau et énergie", "Notre ingénierie conseil intervient notamment pour les études techniques de bâtiment, réseaux d'eau potable, assainissement, installations énergétiques, routes et aménagements. Nous dimensionnons les solutions avec le souci de leur faisabilité, de leur maintenance future et de leur compatibilité avec le budget du projet."], ["Des dossiers qui facilitent la mise en œuvre", "Les études d'ingénierie peuvent comprendre des notes de calcul, plans, quantitatifs, estimations, prescriptions techniques et dossiers d'appel d'offres. Des documents précis facilitent la comparaison des offres, la sélection des entreprises et le contrôle de la qualité pendant les travaux."]] },
  "genie-civil-mali": { eyebrow: "Chantier & contrôle", title: "Génie civil & suivi des travaux au Mali", intro: "Pour vos projets de génie civil au Mali, ICRED assure les études, le suivi des travaux et le contrôle technique nécessaires à une exécution maîtrisée.", keywords: "Génie civil Mali · Bureau d'études génie civil Mali · Suivi travaux Mali · Contrôle travaux Bamako · Ingénieur génie civil Mali", benefits: ["Études de structures et ouvrages", "Suivi de chantier et contrôle qualité", "Rapports réguliers et assistance au maître d'ouvrage"], sections: [["Un chantier sous contrôle", "Nos ingénieurs en génie civil suivent la conformité des travaux avec les plans, les spécifications, les quantités et le calendrier convenu. Lors des visites de chantier, nous observons les points sensibles, relevons les écarts éventuels et formulons des recommandations utiles au maître d'ouvrage et aux entreprises."], ["Un suivi régulier et traçable", "Le suivi des travaux ne consiste pas uniquement à constater l'avancement. ICRED met en place des comptes rendus de visites, rapports d'avancement, tableaux de suivi et échanges structurés avec les intervenants. Cette traçabilité aide à anticiper les retards, à documenter les décisions et à maîtriser les modifications en cours de chantier."], ["Des ouvrages conçus pour durer", "Bâtiments, routes, réseaux, ouvrages d'art et aménagements doivent répondre aux usages prévus et résister aux conditions locales. Nous veillons à la qualité des matériaux, au respect des méthodes d'exécution, à la gestion des interfaces techniques et aux exigences de sécurité tout au long du projet."], ["Assistance au maître d'ouvrage", "ICRED peut représenter les intérêts techniques du client face aux entreprises. Nous participons à l'analyse des offres, aux réunions de chantier, à la vérification des attachements et aux opérations de réception. Vous bénéficiez ainsi d'une lecture indépendante pour prendre des décisions éclairées."]] },
  "etude-faisabilite-mali": { eyebrow: "Décision & stratégie", title: "Études de faisabilité & conseil au Mali", intro: "Avant d'engager un investissement, une étude de faisabilité au Mali vous permet de valider la pertinence, les contraintes et la viabilité de votre projet.", keywords: "Étude de faisabilité Mali · Conseil en ingénierie Mali · Étude de projet Mali · Étude de faisabilité projet · Conseil technique Mali", benefits: ["Analyse des besoins et du contexte", "Évaluation technique, économique et des risques", "Scénarios clairs pour décider sereinement"], sections: [["Sécuriser un investissement dès l'amont", "Une étude de faisabilité permet de vérifier qu'une idée de projet répond à un besoin réel et peut être mise en œuvre dans de bonnes conditions. ICRED analyse le contexte, les bénéficiaires, les objectifs, le site, les ressources nécessaires et les principales contraintes avant que des engagements importants soient pris."], ["Évaluer les options et les risques", "Nous comparons les solutions techniques envisageables et apprécions leurs effets sur le coût, le délai, l'exploitation et la maintenance. L'étude identifie également les risques opérationnels, environnementaux, fonciers ou organisationnels afin de prévoir des mesures réalistes pour les réduire."], ["Un cadre utile pour le financement", "Pour convaincre un partenaire, un bailleur ou une direction, il faut présenter un projet précis et argumenté. Nos études de projet rassemblent les données techniques, les estimations budgétaires, le calendrier indicatif et les hypothèses de mise en œuvre nécessaires à une décision de financement ou de programmation."], ["Passer de la décision à l'action", "À l'issue de la mission, nous proposons un scénario recommandé et une feuille de route. Celle-ci peut inclure les études détaillées à engager, les autorisations à prévoir, le montage de consultation et les étapes de suivi. Vous disposez d'une base concrète pour lancer le projet avec davantage de visibilité."]] },
} as const;

const ServiceDetail = () => {
  const { slug } = useParams();
  const service = services[slug as keyof typeof services];
  usePageSeo(service ? `${service.title} | ICRED Mali` : "Page introuvable | ICRED Mali", service?.intro ?? "", `/${slug ?? ""}`);
  const pageUrl = `https://icred-mali.com/${slug ?? ""}`;
  useStructuredData(`service-schema-${slug}`, service ? {
    "@context": "https://schema.org",
    "@graph": [
      { "@type": "Service", name: service.title, description: service.intro, provider: { "@type": "ProfessionalService", name: "ICRED Mali SARL", telephone: "+22376085847", address: { "@type": "PostalAddress", addressLocality: "Bamako", addressCountry: "ML" } }, areaServed: { "@type": "Country", name: "Mali" }, url: pageUrl },
      { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Accueil", item: "https://icred-mali.com/" }, { "@type": "ListItem", position: 2, name: "Services", item: "https://icred-mali.com/services" }, { "@type": "ListItem", position: 3, name: service.title, item: pageUrl }] },
      { "@type": "FAQPage", mainEntity: [
        { "@type": "Question", name: `Pourquoi faire appel à ICRED pour ${service.title.toLowerCase()} ?`, acceptedAnswer: { "@type": "Answer", text: "ICRED apporte une expertise locale, une méthodologie structurée et un accompagnement adapté aux contraintes de chaque projet au Mali." } },
        { "@type": "Question", name: "Comment demander un devis ou un accompagnement ?", acceptedAnswer: { "@type": "Answer", text: "Contactez ICRED par téléphone, WhatsApp ou via le formulaire de contact afin de présenter votre besoin et recevoir une réponse adaptée." } }
      ] }
    ]
  } : {});
  if (!service) return null;
  return <div className="min-h-screen bg-background"><Navbar /><main>
    <section className="pt-36 pb-20 px-4 bg-gradient-dark text-primary-foreground"><div className="container mx-auto max-w-5xl"><p className="text-secondary font-semibold uppercase tracking-[.2em] text-xs mb-5">{service.eyebrow}</p><h1 className="text-4xl md:text-6xl font-bold max-w-4xl">{service.title}</h1><p className="mt-6 text-lg leading-relaxed text-primary-foreground/75 max-w-3xl">{service.intro}</p><p className="mt-7 text-sm text-primary-foreground/60 border-l-2 border-secondary pl-4">{service.keywords}</p></div></section>
    <section className="section-padding"><div className="container mx-auto max-w-5xl grid lg:grid-cols-[1fr_.7fr] gap-12"><div className="space-y-10">{service.sections.map(([heading, text]) => <article key={heading}><h2 className="text-3xl font-bold mb-4">{heading}</h2><p className="text-muted-foreground leading-8 text-lg">{text}</p></article>)}</div><aside className="rounded-2xl bg-card border border-border p-7 h-fit"><h2 className="text-2xl font-bold mb-6">Notre accompagnement</h2><ul className="space-y-4">{service.benefits.map((benefit) => <li key={benefit} className="flex gap-3 text-foreground/80"><CheckCircle2 className="shrink-0 text-primary" size={20}/>{benefit}</li>)}</ul><a href={whatsappUrl(`Bonjour ICRED, je souhaite parler de mon projet de ${service.title.toLowerCase()}.`)} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex items-center gap-2 bg-gradient-primary text-primary-foreground px-5 py-3 rounded-lg font-semibold">Parler de votre projet <ArrowRight size={17}/></a></aside></div></section>
    <section className="px-4 pb-20"><div className="container mx-auto max-w-5xl bg-green-pale rounded-2xl p-8 md:p-12 flex flex-col md:flex-row justify-between gap-6 items-start"><div><p className="text-primary font-semibold mb-2">ICRED Mali</p><h2 className="text-3xl font-bold">Besoin d'un autre savoir-faire ?</h2></div><Link to="/services" className="inline-flex items-center gap-2 font-semibold text-primary">Voir tous nos services <ArrowRight size={17}/></Link></div></section>
    <section className="px-4 pb-20"><div className="container mx-auto max-w-5xl"><h2 className="text-3xl font-bold mb-7">Questions fréquentes</h2><div className="grid md:grid-cols-2 gap-5"><article className="rounded-xl border border-border bg-card p-6"><h3 className="text-xl font-bold mb-3">Pourquoi choisir ICRED ?</h3><p className="text-muted-foreground leading-relaxed">ICRED associe expertise technique, connaissance du terrain malien et écoute attentive de vos objectifs de projet.</p></article><article className="rounded-xl border border-border bg-card p-6"><h3 className="text-xl font-bold mb-3">Comment obtenir un accompagnement ?</h3><p className="text-muted-foreground leading-relaxed">Présentez-nous votre besoin par téléphone, WhatsApp ou via le formulaire de contact ; notre équipe vous orientera vers la solution adaptée.</p></article></div></div></section>
  </main><Footer /></div>;
};
export default ServiceDetail;
